apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tli666glh-java-quarkus-gitops-repository
spec:
  url: https://github.com/tnevrlka-rhtap/tli666glh-java-quarkus-gitops